# Generated by Django 3.2 on 2021-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempVolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')
                 ),
                ('temp_intake', models.FloatField()),
                ('temp_exhaust', models.FloatField()),
                ('hum_intake', models.FloatField()),
                ('hum_exhaust', models.FloatField()),
                ('vol_intake', models.IntegerField()),
                ('vol_exhaust', models.IntegerField()),
            ],
        ),
    ]
