# Generated by Django 3.2 on 2021-05-09 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_tempvolmodel_cvu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempvolmodel',
            old_name='cvu_name',
            new_name='CVU_name',
        ),
        migrations.AlterField(
            model_name='tempvolmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
