# Generated by Django 3.2 on 2021-12-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20210509_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempvolmodel',
            old_name='CVU_name',
            new_name='AHU_name',
        ),
    ]
